# Generated by Django 4.0 on 2021-12-16 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
