# Generated by Django 4.0 on 2021-12-16 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalApp', '0003_videotape_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videotape',
            name='description',
            field=models.FileField(upload_to='rentalVideotape/media/files/'),
        ),
        migrations.AlterField(
            model_name='videotape',
            name='image',
            field=models.ImageField(upload_to='rentalVideotape/media/images/'),
        ),
    ]
