# Generated by Django 4.0 on 2021-12-17 10:50

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('rentalApp', '0005_alter_videotape_description_alter_videotape_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='buyer_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='RU'),
        ),
    ]
