# Generated by Django 4.0 on 2021-12-17 10:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalApp', '0006_alter_rental_buyer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='buyer_phone',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')]),
        ),
    ]
