# Generated by Django 4.0 on 2021-12-17 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentalApp', '0007_alter_rental_buyer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='videotape',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rentalApp.videotape', unique=True),
        ),
    ]
